# This workflow will run validations against all hyperlinks in markdown files (include Wiki pages)

name: markdown-hyperlink-auditor

# Controls when the workflow will run
on:
  workflow_dispatch: { }
  push:

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Dependent
        run: |
          python -m pip install --upgrade pip
          echo "FAILED=0" >> $GITHUB_ENV
      - name: Downloader
        run: curl -O https://raw.githubusercontent.com/thevickypedia/none-shall-pass/main/src/validator.py
      - name: Validator
        run: |
          pwd
          ls -ltrh
          echo "Exit Code: ${{ env.FAILED }}"
          echo "github.event.repository.name: ${{ github.event.repository.name }}"
          echo "github.event.repository.owner: ${{ github.event.repository.owner }}"
          echo "github.repository: ${{ github.repository }}"
      - name: Checker
        if: ${{ env.FAILED != '0' }}
        run: |
          echo "Non zero exit code: ${{ env.FAILED }}"
          exit 1
